### ISSUE TITLE
Why it can't copy all js and css to right place.

### ISSUE THREAD

**Issue by zchking** [SnowdogApps/magento2-frontools#141] opened 2016-12-19 01:58 UTC
I use it to deploy my static file, but most js file of them show me 404 Not found after 

> gulp deploy

This is my theme config file:

![image](https://cloud.githubusercontent.com/assets/5665818/21298919/5ba3c30e-c5d1-11e6-9faf-d6d631410a6d.png)

**Comment by zchking** [comment] 2016-12-19 01:59
I need use it to deploy and merge my js and css as magento2's merge is not working correctly, any one know what's the problem is ? thank you very much:)

**Comment by Igloczek** [comment] 2016-12-19 14:47
Tools are not (yet) replacement of Magento CLI, it can take care of JS inside your theme, not inherited from core.

You have to enable developer mode (recommended) or use `bin/magento setup:static-content:deploy`.

Same thing about merging, read docs and you will understand how it works.

Also you should try to describe your problems a bit better, b/c saying "not working correctly, any one know what's the problem is", does not help at all, b/c I'm in "anyone" group too and merging works fine for me and I probably know why you though it doesn't work 😉 

I heavily recommend to follow the [docs](http://devdocs.magento.com/) and back here where you were familiar with core.
This tools are oriented to developers with serious M2 experience, b/c I have limited time and can't spend them on support.

Closing this due it's not a issue related to tools itself.

**Closed by Igloczek** 2016-12-19 14:47 UTC
