### ISSUE TITLE
wrong path in theme.json ?

### ISSUE THREAD

**Issue by to8gal** [SnowdogApps/magento2-frontools#93] opened 2016-09-29 16:04 UTC
Hello,

being this:
```
"src"    : "app/design/frontend/a/b",
    "dest"   : "pub/static/frontend/a/b",
	"parent" : "framework",
    "locale" : ["en_US"],
    "lang"   : "scss",
    "area"   : "frontend",
    "vendor" : "a",
    "name"   : "b",
    "files"  : [
      "css/source/_email-variables",
      "css/source/_extend",
	  "css/source/_theme",
	  "css/source/_variables",
	  "css/source/_widgets",
	  "css/source/components/_modals",
	  "css/source/lib",
	  "css/source/lib/variables"
```
my themes.json

Then I deploy with Gulp, (and still some file like some js stay out of the folder, dunno why,
anyway on gulp watch still copy the file  in pub/static/frontend/a/b/web/css/source so I try and change app/design/frontend/a/b to app/design/frontend/a/b/web, but still copy files in pub/static/frontend/a/b/css/source.

I also wanna notice if I put web "src"    : "app/design/frontend/a/b/web" before deploy it will copy anything at all

I don´t get any other way to do it, I tried several.

Thanks

**Comment by Igloczek** [comment] 2016-09-30 10:08
Please read documentation. `area`, `vendor`, `name` and `files` are useless for SASS themes.

Which version of theme and Frontools are you using? If current, you styles should be placed in `/styles` not `/web/css`.

**Comment by to8gal** [comment] 2016-09-30 11:40
Yes I know the are vendor etc are no use, but still path was respected anyway:

I downloaded your theme and changed my structure to your theme structure, so eliminated the "source" folder and put all together in a "styles" folder so it could copy on the right path but still no success, it always generate the same css files: camera, grid, theme-styles and modules,

**Comment by Igloczek** [comment] 2016-10-24 09:48
Your theme or tools are outdated or modified in some weird way.
I'm closing it, b/c it's not a bug for me.

If you need some help with usage, ask question on forum.

**Closed by Igloczek** 2016-10-24 09:48 UTC
