### ISSUE TITLE
Slow and repetitive behaviour

### ISSUE THREAD

**Issue by DocOlson** [SnowdogApps/magento2-frontools#290] opened 2018-03-08 16:58 UTC
I just set everything up according to the readme. I have a basic theme that is based on the 

```
{
  "blank": {
    "src": "vendor/snowdog/theme-blank-sass",
    "dest": "pub/static/frontend/Snowdog/blank",
    "locale": ["en_US"],
    "ignore": [".test"]
  },
  "mytheme": {
    "src": "app/design/frontend/om/mytheme",
    "dest": "pub/static/frontend/om/mytheme",
    "locale": ["de_DE"],
    "parent": "blank"
  }
}
```
Now when I start gulp watch and make a change to any file within my theme folder on the console I get a bazillion "Change detected." messages. It seems EVERY file is detected as changed. Then the lint plugin seems to work on every file ("Theme: maytheme File: _module.scss - SASS Lint finished.") followed by just as many warnings and errors (mostly "warning  !important not allowed  no-important"). 

Then it does not seem to do anything. The styles.css is NOT updated. But after a while (minutes) it all of a sudden I get this message A LOT: "Theme: mytheme styles.css Compiled!". Over and over again. It eventually stops and has updated the styles.css file which is around 2MB in size.

I am used to gulp being lighting fast so I must assume something is very wrong here.

Any idea?

**Comment by Igloczek** [comment] 2018-03-08 17:01
Let's read this thread https://github.com/SnowdogApps/magento2-frontools/issues/257

**Comment by DocOlson** [comment] 2018-03-11 13:57
I did but I am not a single bit smarter now.

**Comment by Igloczek** [comment] 2018-03-11 14:40
I'm also not a single bit smarter after reading your answer 😉 
Tell me what is your stack, OS, editor, what of the proposed workarounds did you try and then maybe I will be able to help you.

**Comment by DocOlson** [comment] 2018-03-12 08:39
OS: Debian Linux.
Editor: PHP Storm (Windows) via samba share.
I just realized the "safe write" option in PHPStorm actually made a difference.

But now I get "Expected indentation of 12 spaces but found 6" errors en masse. I assume this has to do with linting? How can I disable linting? I really don't need it.

Thank you.

**Comment by Igloczek** [comment] 2018-03-13 15:58
Yup, that's the linters output and you shouldn't ignore it, but if you really want to just read the docs to find the flag that will disable linting.

Closing this, b/c that's the issue caused by PHP Storm, not a Frontools bug.

**Closed by Igloczek** 2018-03-13 15:58 UTC
